### ISSUE TITLE
Accessing vagrant version on dashboard?

### ISSUE THREAD

**Issue by dingo-d** [Varying-Vagrant-Vagrants/dashboard#2]
I'd like to add info on my dashboard, so I added `info.php` in the default dashboard inside `php/blocks/sidebar/` and included it in `dashboard-default.php`

Now, getting php version is easy: `$php_ver = phpversion();` and just echoing it out.

But how can I get the `vagrant` and `virtualBox` versions? I cannot access them from within the vagrant so `$vagrant_version = shell_exec( "vagrant --version 2>&1" );` won't cut it.

Any way to do this?

**Comment by tomjn** [comment]
Hmm I forgot issues was still enabled on this repo. I'm not aware of a
mechanism to get this information without VVV writing it somewhere.

Shell exec will never work as it runs inside the VM not outside

**Comment by dingo-d** [comment]
> Shell exec will never work as it runs inside the VM not outside

Yup, figured out after I got the error from the `shell_exec` 😄 

Hmmm I could try to write a utility that stores it on provision, I guess :S Just spitballing here XD

**Comment by tomjn** [comment]
<img width="422" alt="screen shot 2018-06-26 at 13 33 50" src="https://user-images.githubusercontent.com/58855/41911925-eda0d444-7945-11e8-988b-339bbb3919f0.png">
