### ISSUE TITLE
Mailcatcher link still showing instead of Mailhog

### ISSUE THREAD

**Issue by joelworsham** [Varying-Vagrant-Vagrants/dashboard#4]
I see you added a check for Mailhog installation, but I'm not certain it is working. At least, it isn't for me.

Mailcatcher still shows as the only option, BUT, if I visit http://vvv.test:8025/ MailHog *does* in fact load

**Comment by joelworsham** [comment]
![](https://d.pr/i/XIoL9H+)
![](https://d.pr/i/wkyUDo+)

**Comment by tomjn** [comment]
I set it to show one or the other but not both, since MailHog is meant to replace MailCatcher, but the dashboard might update and run on an older VVV that still uses MailCatcher.

So it detects if MailCatcher is present and shows the button, but if it isn't, it runs a similar check for MailHog

Give that you have both operational, when you send an email via WP, which one receives it?

**Comment by tomjn** [comment]
hmmm, it might make sense to reverse the order of the check then, in the meantime the search for a good way to uninstall mailcatcher continues

**Comment by tomjn** [comment]
hmmm it is already that way:

```php
	<?php
	if ( file_exists( '/usr/local/bin/mailhog' ) ) {
		?>
		<a class="button" href="http://vvv.test:8025" target="_blank">MailHog</a>
		<?php
	} else if ( file_exists( '/usr/local/rvm/bin/mailcatcher' ) ) {
		?>
		<a class="button" href="http://vvv.test:1080" target="_blank">Mailcatcher</a>
		<?php
	}
```

https://github.com/Varying-Vagrant-Vagrants/dashboard/blob/develop/php/blocks/sidebar/bundled-tools.php#L7

Perhaps your dashboard is in need of an update, can you confirm the branch it is on and if a `git pull` resolves this?

**Comment by joelworsham** [comment]
haha yeah that's what I thought. I did just pull the `develop` branch of this repo before opening this issue.

**Comment by cfoellmann** [comment]
Is this resolved?

**Comment by joelworsham** [comment]
I can at least say it is working for me now.

**Comment by cfoellmann** [comment]
So we close this until anyone else has the same/similar issue.

**Comment by tomjn** [comment]
Note that the dashboard doesn't follow the standard VVV release cycle as it's a separate repository, a reprovision usually is enough to pull down a newer version
